name: Package controller-runtime envtest

on:
  push:
    branches:
      - main
    paths:
      - 'hack/envtest/_matrix/*.yaml'

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf # tag=v45.0.4
        with:
          files: |
            hack/envtest/_matrix/*.yaml
      - name: Setup package release version
        id: release-version
        run: |
            if [[ ${{ steps.changed-files.outputs.all_changed_files_count }} != 1 ]]; then
              echo "One Kubernetes patch version files should be changed for a release, found ${{ steps.changed-files.outputs.all_changed_files_count }}"
              exit 1
            fi

            for changed_file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              export KUBERNETES_VERSION=$(echo "${changed_file}" | grep -oP '(?<=/)[^/]+(?=\.yaml)')
              echo "KUBERNETES_VERSION=$KUBERNETES_VERSION" >> $GITHUB_ENV
            done
      - name: Build packages
        run: |
          make release-envtest KUBERNETES_VERSION=${{ env.KUBERNETES_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # tag=v2.0.9
        with:
          tag_name: envtest-${{ env.KUBERNETES_VERSION }}
          draft: false
          make_latest: false
          files: |
            out/envtest-*.tar.gz
            out/envtest-*.tar.gz.sha512
          fail_on_unmatched_files: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # tag=v7.0.5
        with:
          commit-message: Promote envtest release for Kubernetes ${{ env.KUBERNETES_VERSION }}
          title: ":seedling: Promotion of envtest release for Kubernetes ${{ env.KUBERNETES_VERSION }}"
          body: |
            This PR promotes the envtest release for Kubernetes ${{ env.KUBERNETES_VERSION }}.
          branch: promote-envtest-${{ env.KUBERNETES_VERSION }}
          add-paths: |
            envtest-releases.yaml
